version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    networks:
      - mern-network
    depends_on:
      - backend

networks:
  mern-network:
    driver: bridge
